<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="date" content="2015-02-13" />

<title>Practical Machine Learning Assignment</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; }
code > span.dt { color: #902000; }
code > span.dv { color: #40a070; }
code > span.bn { color: #40a070; }
code > span.fl { color: #40a070; }
code > span.ch { color: #4070a0; }
code > span.st { color: #4070a0; }
code > span.co { color: #60a0b0; font-style: italic; }
code > span.ot { color: #007020; }
code > span.al { color: #ff0000; font-weight: bold; }
code > span.fu { color: #06287e; }
code > span.er { color: #ff0000; font-weight: bold; }
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link href="data:text/css,body%20%7B%0A%20%20background%2Dcolor%3A%20%23fff%3B%0A%20%20margin%3A%201em%20auto%3B%0A%20%20max%2Dwidth%3A%20700px%3B%0A%20%20overflow%3A%20visible%3B%0A%20%20padding%2Dleft%3A%202em%3B%0A%20%20padding%2Dright%3A%202em%3B%0A%20%20font%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0A%20%20font%2Dsize%3A%2014px%3B%0A%20%20line%2Dheight%3A%201%2E35%3B%0A%7D%0A%0A%23header%20%7B%0A%20%20text%2Dalign%3A%20center%3B%0A%7D%0A%0A%23TOC%20%7B%0A%20%20clear%3A%20both%3B%0A%20%20margin%3A%200%200%2010px%2010px%3B%0A%20%20padding%3A%204px%3B%0A%20%20width%3A%20400px%3B%0A%20%20border%3A%201px%20solid%20%23CCCCCC%3B%0A%20%20border%2Dradius%3A%205px%3B%0A%0A%20%20background%2Dcolor%3A%20%23f6f6f6%3B%0A%20%20font%2Dsize%3A%2013px%3B%0A%20%20line%2Dheight%3A%201%2E3%3B%0A%7D%0A%20%20%23TOC%20%2Etoctitle%20%7B%0A%20%20%20%20font%2Dweight%3A%20bold%3B%0A%20%20%20%20font%2Dsize%3A%2015px%3B%0A%20%20%20%20margin%2Dleft%3A%205px%3B%0A%20%20%7D%0A%0A%20%20%23TOC%20ul%20%7B%0A%20%20%20%20padding%2Dleft%3A%2040px%3B%0A%20%20%20%20margin%2Dleft%3A%20%2D1%2E5em%3B%0A%20%20%20%20margin%2Dtop%3A%205px%3B%0A%20%20%20%20margin%2Dbottom%3A%205px%3B%0A%20%20%7D%0A%20%20%23TOC%20ul%20ul%20%7B%0A%20%20%20%20margin%2Dleft%3A%20%2D2em%3B%0A%20%20%7D%0A%20%20%23TOC%20li%20%7B%0A%20%20%20%20line%2Dheight%3A%2016px%3B%0A%20%20%7D%0A%0Atable%20%7B%0A%20%20margin%3A%201em%20auto%3B%0A%20%20border%2Dwidth%3A%201px%3B%0A%20%20border%2Dcolor%3A%20%23DDDDDD%3B%0A%20%20border%2Dstyle%3A%20outset%3B%0A%20%20border%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0A%20%20border%2Dwidth%3A%202px%3B%0A%20%20padding%3A%205px%3B%0A%20%20border%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0A%20%20border%2Dwidth%3A%201px%3B%0A%20%20border%2Dstyle%3A%20inset%3B%0A%20%20line%2Dheight%3A%2018px%3B%0A%20%20padding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0A%20%20border%2Dleft%2Dstyle%3A%20none%3B%0A%20%20border%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0A%20%20background%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0A%0Ap%20%7B%0A%20%20margin%3A%200%2E5em%200%3B%0A%7D%0A%0Ablockquote%20%7B%0A%20%20background%2Dcolor%3A%20%23f6f6f6%3B%0A%20%20padding%3A%200%2E25em%200%2E75em%3B%0A%7D%0A%0Ahr%20%7B%0A%20%20border%2Dstyle%3A%20solid%3B%0A%20%20border%3A%20none%3B%0A%20%20border%2Dtop%3A%201px%20solid%20%23777%3B%0A%20%20margin%3A%2028px%200%3B%0A%7D%0A%0Adl%20%7B%0A%20%20margin%2Dleft%3A%200%3B%0A%7D%0A%20%20dl%20dd%20%7B%0A%20%20%20%20margin%2Dbottom%3A%2013px%3B%0A%20%20%20%20margin%2Dleft%3A%2013px%3B%0A%20%20%7D%0A%20%20dl%20dt%20%7B%0A%20%20%20%20font%2Dweight%3A%20bold%3B%0A%20%20%7D%0A%0Aul%20%7B%0A%20%20margin%2Dtop%3A%200%3B%0A%7D%0A%20%20ul%20li%20%7B%0A%20%20%20%20list%2Dstyle%3A%20circle%20outside%3B%0A%20%20%7D%0A%20%20ul%20ul%20%7B%0A%20%20%20%20margin%2Dbottom%3A%200%3B%0A%20%20%7D%0A%0Apre%2C%20code%20%7B%0A%20%20background%2Dcolor%3A%20%23f7f7f7%3B%0A%20%20border%2Dradius%3A%203px%3B%0A%20%20color%3A%20%23333%3B%0A%7D%0Apre%20%7B%0A%20%20white%2Dspace%3A%20pre%2Dwrap%3B%20%20%20%20%2F%2A%20Wrap%20long%20lines%20%2A%2F%0A%20%20border%2Dradius%3A%203px%3B%0A%20%20margin%3A%205px%200px%2010px%200px%3B%0A%20%20padding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0A%20%20background%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0A%0Acode%20%7B%0A%20%20font%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0A%20%20font%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0A%20%20padding%3A%202px%200px%3B%0A%7D%0A%0Adiv%2Efigure%20%7B%0A%20%20text%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0A%20%20background%2Dcolor%3A%20%23FFFFFF%3B%0A%20%20padding%3A%202px%3B%0A%20%20border%3A%201px%20solid%20%23DDDDDD%3B%0A%20%20border%2Dradius%3A%203px%3B%0A%20%20border%3A%201px%20solid%20%23CCCCCC%3B%0A%20%20margin%3A%200%205px%3B%0A%7D%0A%0Ah1%20%7B%0A%20%20margin%2Dtop%3A%200%3B%0A%20%20font%2Dsize%3A%2035px%3B%0A%20%20line%2Dheight%3A%2040px%3B%0A%7D%0A%0Ah2%20%7B%0A%20%20border%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0A%20%20padding%2Dtop%3A%2010px%3B%0A%20%20padding%2Dbottom%3A%202px%3B%0A%20%20font%2Dsize%3A%20145%25%3B%0A%7D%0A%0Ah3%20%7B%0A%20%20border%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0A%20%20padding%2Dtop%3A%2010px%3B%0A%20%20font%2Dsize%3A%20120%25%3B%0A%7D%0A%0Ah4%20%7B%0A%20%20border%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0A%20%20margin%2Dleft%3A%208px%3B%0A%20%20font%2Dsize%3A%20105%25%3B%0A%7D%0A%0Ah5%2C%20h6%20%7B%0A%20%20border%2Dbottom%3A%201px%20solid%20%23ccc%3B%0A%20%20font%2Dsize%3A%20105%25%3B%0A%7D%0A%0Aa%20%7B%0A%20%20color%3A%20%230033dd%3B%0A%20%20text%2Ddecoration%3A%20none%3B%0A%7D%0A%20%20a%3Ahover%20%7B%0A%20%20%20%20color%3A%20%236666ff%3B%20%7D%0A%20%20a%3Avisited%20%7B%0A%20%20%20%20color%3A%20%23800080%3B%20%7D%0A%20%20a%3Avisited%3Ahover%20%7B%0A%20%20%20%20color%3A%20%23BB00BB%3B%20%7D%0A%20%20a%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0A%20%20%20%20text%2Ddecoration%3A%20underline%3B%20%7D%0A%20%20a%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0A%20%20%20%20text%2Ddecoration%3A%20underline%3B%20%7D%0A%0A%2F%2A%20Class%20described%20in%20https%3A%2F%2Fbenjeffrey%2Ecom%2Fposts%2Fpandoc%2Dsyntax%2Dhighlighting%2Dcss%0A%20%20%20Colours%20from%20https%3A%2F%2Fgist%2Egithub%2Ecom%2Frobsimmons%2F1172277%20%2A%2F%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%2F%2A%20Keyword%20%2A%2F%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%2F%2A%20DataType%20%2A%2F%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%2F%2A%20DecVal%20%28decimal%20values%29%20%2A%2F%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20BaseN%20%2A%2F%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20Float%20%2A%2F%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20Char%20%2A%2F%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%2F%2A%20String%20%2A%2F%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%2F%2A%20Comment%20%2A%2F%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%2F%2A%20OtherToken%20%2A%2F%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%2F%2A%20AlertToken%20%2A%2F%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%2F%2A%20Function%20calls%20%2A%2F%20%0Acode%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%2F%2A%20ErrorTok%20%2A%2F%0A%0A" rel="stylesheet" type="text/css" />

</head>

<body>



<div id="header">
<h1 class="title">Practical Machine Learning Assignment</h1>
<h4 class="date"><em>2015-02-13</em></h4>
</div>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>In this assignment I used R version 3.1.2 and <strong>caret</strong> version 6.0-41. I followed the classification model building approach described by the author of the caret package<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>. The process consisted of data preparation, building and tuning the model using the <em>train</em> function, predicting new samples using the <em>predict</em> function, and characterizing model performance using the <em>confusionMatrix</em> function.</p>
</div>
<div id="data-preparation" class="section level2">
<h2>Data preparation</h2>
<p>As a first step in processing the the data set, I removed all of the non-numerical variables and variables with very few values. This resulted in a data frame with 52 predictor variables and the outcome variable (classe).</p>
<pre><code>##  [1] &quot;roll_belt&quot;            &quot;pitch_belt&quot;           &quot;yaw_belt&quot;            
##  [4] &quot;total_accel_belt&quot;     &quot;gyros_belt_x&quot;         &quot;gyros_belt_y&quot;        
##  [7] &quot;gyros_belt_z&quot;         &quot;accel_belt_x&quot;         &quot;accel_belt_y&quot;        
## [10] &quot;accel_belt_z&quot;         &quot;magnet_belt_x&quot;        &quot;magnet_belt_y&quot;       
## [13] &quot;magnet_belt_z&quot;        &quot;roll_arm&quot;             &quot;pitch_arm&quot;           
## [16] &quot;yaw_arm&quot;              &quot;total_accel_arm&quot;      &quot;gyros_arm_x&quot;         
## [19] &quot;gyros_arm_y&quot;          &quot;gyros_arm_z&quot;          &quot;accel_arm_x&quot;         
## [22] &quot;accel_arm_y&quot;          &quot;accel_arm_z&quot;          &quot;magnet_arm_x&quot;        
## [25] &quot;magnet_arm_y&quot;         &quot;magnet_arm_z&quot;         &quot;roll_dumbbell&quot;       
## [28] &quot;pitch_dumbbell&quot;       &quot;yaw_dumbbell&quot;         &quot;total_accel_dumbbell&quot;
## [31] &quot;gyros_dumbbell_x&quot;     &quot;gyros_dumbbell_y&quot;     &quot;gyros_dumbbell_z&quot;    
## [34] &quot;accel_dumbbell_x&quot;     &quot;accel_dumbbell_y&quot;     &quot;accel_dumbbell_z&quot;    
## [37] &quot;magnet_dumbbell_x&quot;    &quot;magnet_dumbbell_y&quot;    &quot;magnet_dumbbell_z&quot;   
## [40] &quot;roll_forearm&quot;         &quot;pitch_forearm&quot;        &quot;yaw_forearm&quot;         
## [43] &quot;total_accel_forearm&quot;  &quot;gyros_forearm_x&quot;      &quot;gyros_forearm_y&quot;     
## [46] &quot;gyros_forearm_z&quot;      &quot;accel_forearm_x&quot;      &quot;accel_forearm_y&quot;     
## [49] &quot;accel_forearm_z&quot;      &quot;magnet_forearm_x&quot;     &quot;magnet_forearm_y&quot;    
## [52] &quot;magnet_forearm_z&quot;</code></pre>
<p>Subsequently, I split the training data into a training set (70% of values) and a test set (30% of values) using the createDataPartition function. This resulted in 13737 observations in the training set and 5885 observations in the test set.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">400</span>)
inTrain &lt;-<span class="st"> </span><span class="kw">createDataPartition</span>(<span class="dt">y=</span>pml.training.cleaned$classe, <span class="dt">p=</span><span class="fl">0.7</span>, <span class="dt">list=</span>F)
training &lt;-<span class="st"> </span>pml.training.cleaned[inTrain,]
testing &lt;-<span class="st"> </span>pml.training.cleaned[-inTrain,]</code></pre>
</div>
<div id="model-building" class="section level2">
<h2>Model building</h2>
<p>Based on the analysis by Fernández-Delgado et al.<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a> and the video lectures, I decided to use a random forest classifier (model <strong>rf</strong> in caret, provided by the <strong>randomForest</strong> package version 4.6-10).</p>
<p>I used 10-fold cross-validation with 3 repeats to tune the model parameters and select the optimal model based on accuracy. Using 3 repeats should help reduce variance in the resampling estimates<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a>. The default value of 500 trees was used.</p>
<p>I chose a relatively low <em>tuneLength</em> of 5 to keep the computation time reasonable. Even when utilizing three cores via the <strong>doParallel</strong> package (1.0.8), computing the model took 1 hour 15 minutes on a 2.6 GHz Intel Core i5.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(doParallel)
<span class="kw">registerDoParallel</span>(<span class="dv">3</span>)
rfFit &lt;-<span class="st"> </span><span class="kw">train</span>(classe ~<span class="st"> </span>.,<span class="dt">data=</span>training, <span class="dt">method=</span><span class="st">&quot;rf&quot;</span>,
               <span class="dt">trControl=</span><span class="kw">trainControl</span>(<span class="dt">method=</span><span class="st">&quot;repeatedcv&quot;</span>, <span class="dt">number=</span><span class="dv">10</span>, <span class="dt">repeats=</span><span class="dv">3</span>), <span class="dt">tuneLength=</span><span class="dv">5</span>)</code></pre>
<p>Table 1 shows the resampling results across tuning parameters. The final model utilizes <em>mtry</em> value of 14 (i.e., number of predictors randomly sampled for splitting at each node).</p>
<table>
<caption><em>Table 1.</em> Resampling results</caption>
<thead>
<tr class="header">
<th align="right">mtry</th>
<th align="right">Accuracy</th>
<th align="right">Kappa</th>
<th align="right">AccuracySD</th>
<th align="right">KappaSD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2</td>
<td align="right">0.992</td>
<td align="right">0.989</td>
<td align="right">0.002</td>
<td align="right">0.003</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">0.993</td>
<td align="right">0.992</td>
<td align="right">0.002</td>
<td align="right">0.003</td>
</tr>
<tr class="odd">
<td align="right">27</td>
<td align="right">0.992</td>
<td align="right">0.989</td>
<td align="right">0.002</td>
<td align="right">0.003</td>
</tr>
<tr class="even">
<td align="right">39</td>
<td align="right">0.990</td>
<td align="right">0.987</td>
<td align="right">0.002</td>
<td align="right">0.003</td>
</tr>
<tr class="odd">
<td align="right">52</td>
<td align="right">0.985</td>
<td align="right">0.980</td>
<td align="right">0.003</td>
<td align="right">0.004</td>
</tr>
</tbody>
</table>
<p>The final model estimates an out-of-bag error rate of 0.59%. OOB error is estimated during the training by bootstrapping from the training set and it should provide an unbiased estimate of out-of-sample error<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a>. The class error rate ranged from &lt; 0.1% (class A) to ~1% (classes B, D).</p>
</div>
<div id="performance" class="section level2">
<h2>Performance</h2>
<p>The classification performance of the random forest model was used to predict the classes in the test set as follows:</p>
<pre class="sourceCode r"><code class="sourceCode r">rfPredict &lt;-<span class="st"> </span><span class="kw">predict</span>(rfFit, <span class="dt">newdata=</span>testing)
rfPerformance &lt;-<span class="st"> </span><span class="kw">confusionMatrix</span>(rfPredict,testing$classe)</code></pre>
<p>The overall accuracy of the model was 99.4% (κ = 0.99), which is contingent with the model’s estimated OOB error. Balanced accuracy ranged between 99.3% and 99.9% by class (Table 2).</p>
<table>
<caption><em>Table 2.</em> Statistics by class</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Class: A</th>
<th align="right">Class: B</th>
<th align="right">Class: C</th>
<th align="right">Class: D</th>
<th align="right">Class: E</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Sensitivity</td>
<td align="right">1.000</td>
<td align="right">0.996</td>
<td align="right">0.988</td>
<td align="right">0.991</td>
<td align="right">0.993</td>
</tr>
<tr class="even">
<td align="left">Specificity</td>
<td align="right">0.999</td>
<td align="right">0.999</td>
<td align="right">0.998</td>
<td align="right">0.998</td>
<td align="right">1.000</td>
</tr>
<tr class="odd">
<td align="left">Pos Pred Value</td>
<td align="right">0.997</td>
<td align="right">0.994</td>
<td align="right">0.990</td>
<td align="right">0.988</td>
<td align="right">1.000</td>
</tr>
<tr class="even">
<td align="left">Neg Pred Value</td>
<td align="right">1.000</td>
<td align="right">0.999</td>
<td align="right">0.998</td>
<td align="right">0.998</td>
<td align="right">0.998</td>
</tr>
<tr class="odd">
<td align="left">Prevalence</td>
<td align="right">0.284</td>
<td align="right">0.194</td>
<td align="right">0.174</td>
<td align="right">0.164</td>
<td align="right">0.184</td>
</tr>
<tr class="even">
<td align="left">Detection Rate</td>
<td align="right">0.284</td>
<td align="right">0.193</td>
<td align="right">0.172</td>
<td align="right">0.162</td>
<td align="right">0.182</td>
</tr>
<tr class="odd">
<td align="left">Detection Prevalence</td>
<td align="right">0.285</td>
<td align="right">0.194</td>
<td align="right">0.174</td>
<td align="right">0.164</td>
<td align="right">0.182</td>
</tr>
<tr class="even">
<td align="left">Balanced Accuracy</td>
<td align="right">0.999</td>
<td align="right">0.997</td>
<td align="right">0.993</td>
<td align="right">0.994</td>
<td align="right">0.996</td>
</tr>
</tbody>
</table>
</div>
<div id="model-comparison" class="section level2">
<h2>Model comparison</h2>
<p>For comparison purposes I also trained a support vector machine (SVM) classifier and a k-Nearest neighbor classifiers using the same training and test sets. My primary goals was to examine if comparable performance to random forests could be reached with a computationally less demanding models.</p>
<p>Training and test sets were pre-processed (centered and scaled) prior to training in order to improve accuracy. I used the radial basis function kernel (RBF) model <strong>svmRadial</strong>, provided by <strong>kernlab</strong> (0.9-20) to train the SVM classifier and the <strong>knn</strong> model from <strong>e1071</strong> (1.6-4).</p>
<p>Similarly to the random forest model, I used 10-fold cross-validation with 3 repeats to tune the SVM <em>cost</em> parameter (i.e., level of trade-off between training error and complexity of the model) and the k-NN <em>k</em> parameter (i.e., number of neighbors). The training time was approximately 40 minutes for the SVM model and 10 minutes for the k-NN model using the same multicore configuration as the random forest model.</p>
<pre class="sourceCode r"><code class="sourceCode r">svmFit &lt;-<span class="st"> </span><span class="kw">train</span>(classe ~<span class="st"> </span>.,<span class="dt">data=</span>training.processed,<span class="dt">method=</span><span class="st">&quot;svmRadial&quot;</span>,
                <span class="dt">trControl=</span><span class="kw">trainControl</span>(<span class="dt">method=</span><span class="st">&quot;repeatedcv&quot;</span>,<span class="dt">number=</span><span class="dv">10</span>,<span class="dt">repeats=</span><span class="dv">3</span>),<span class="dt">tuneLength=</span><span class="dv">10</span>)
knnFit &lt;-<span class="st"> </span><span class="kw">train</span>(classe ~.,<span class="dt">data=</span>training.processed,<span class="dt">method=</span><span class="st">&quot;knn&quot;</span>,
                <span class="dt">trControl=</span><span class="kw">trainControl</span>(<span class="dt">method=</span><span class="st">&quot;repeatedcv&quot;</span>,<span class="dt">number=</span><span class="dv">10</span>,<span class="dt">repeats=</span><span class="dv">3</span>),<span class="dt">tuneLength=</span><span class="dv">10</span>)</code></pre>
<p>The best SVM model uses 2999 support vectors and has a cost of 128, with a training error of 0.15%. The resampled overall accuracy is 99.2% (κ = 0.99). When predicted on the test set, the overall accuracy of the model was 99.3% (κ = 0.99), with balanced accuracy ranging between 98.8% and 99.9% by class.</p>
<p>The best k-nearest neighbor model uses 5 neighbours. The resampled overall accuracy is 96.0% (κ = 0.95). When predicting on the test set, the overall accuracy was 96.4% (κ = 0.95). The balanced accuracy ranged from 96.9% to 98.5%.</p>
<p>The models were compared using the <em>resamples</em> and <em>diff</em> functions, as per the caret documentation<a href="#fn5" class="footnoteRef" id="fnref5"><sup>5</sup></a>. The difference between SVM and random forest was not statistically significant, however k-nearest neighbour was worse than both.</p>
<pre class="sourceCode r"><code class="sourceCode r">resamps &lt;-<span class="st"> </span><span class="kw">resamples</span>(<span class="kw">list</span>(<span class="dt">KNN =</span> knnFit, <span class="dt">RF =</span> rfFit, <span class="dt">SVM =</span> svmFit))
difs &lt;-<span class="st"> </span><span class="kw">diff</span>(resamps)</code></pre>
<p>When predicting on the “unseen” data provided as the programming assignment problems, all of the classifiers worked as could be expected. Neither SVM or random forest produced any misclassifications while the k-nearest neighbor model predicted problem 3 incorrectly.</p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>All of the classifier models produce excellent classification results with little need for manual tuning. In practical terms, k-nearest neighbor is the fastest to compute seems less accurate than the others. SVM appears to be faster to compute than random forest even if the number of levels for the tuning parameter is increased. Compared to SVN, random forest may have advantages in support for automatic feature selection and robustness to predictor noise (Kuhn and Johnson, p. 550<a href="#fn6" class="footnoteRef" id="fnref6"><sup>6</sup></a>).</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Kuhn, M.: Building Predictive Models in R Using the caret package. Journal of Statistical Software 28(5), November 2008. <a href="http://www.jstatsoft.org/v28/i05/paper">http://www.jstatsoft.org/v28/i05/paper</a><a href="#fnref1">↩</a></p></li>
<li id="fn2"><p>Fernández-Delgado, M., Cernadas, E., Barro, S., Amorim, D.: Do we Need Hundreds of Classifiers to Solve Real World Classification Problems? Journal of Machile Learning Research 15, October, 3133-3181 (2014). <a href="http://jmlr.org/papers/volume15/delgado14a/delgado14a.pdf">http://jmlr.org/papers/volume15/delgado14a/delgado14a.pdf</a><a href="#fnref2">↩</a></p></li>
<li id="fn3"><p>Kuhn, M.: <a href="http://appliedpredictivemodeling.com/blog/2014/11/27/vpuig01pqbklmi72b8lcl3ij5hj2qm">Comparing Different Species of Cross-Validation</a><a href="#fnref3">↩</a></p></li>
<li id="fn4"><p>Breiman, L., Cutler, A.: Random Forests. <a href="http://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm#ooberr">http://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm#ooberr</a><a href="#fnref4">↩</a></p></li>
<li id="fn5"><p><a href="http://topepo.github.io/caret/training.html">http://topepo.github.io/caret/training.html</a><a href="#fnref5">↩</a></p></li>
<li id="fn6"><p>Kuhn, M., Johnson, K.: Applied Predictive Modeling. Springer, New York (2013)<a href="#fnref6">↩</a></p></li>
</ol>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
